### ISSUE TITLE
Pechakucha

### ISSUE THREAD

**Issue by prow-aniss** [csctd/profile-website-prow-aniss#7]
Here's how I wanna format it:
- [x] Start of move in day
- [x] Massive rain after Edwards presentation
- [x] My miserable first day, not having my ID or basically much of anything
- [x] The grind of waking up at 7 AM every morning 
- [x] My first impressions of classes and formatting your time
- [x] First foray into exploring the library
- [x] First foray into exploring campus
- [x] Dog Atle
- [x] My yoyo and how much I've used it
- [x] My cozy spot in the library, despite knowing I won't have it nearly as much in the Fall
- [x] The many, many daily writings and reflections I had to do for my classes
- [x] Tie dye and how stained my hands got
- [x] Dining hall (hit or miss)
- [x] Getting vertigo and missing a bunch of classes
- [x] Fire alarm at 6 in the morning
- [x] Butterdog in Kahoot
- [x] Dorm life!
- [x] The lounges (and how crowded they were)
- [ ] The memories I made, having campus basically to ourselves is super chill
- [x] Compsci classes and bugfixing

**Comment by brownsarahm** [comment]
great work! Next step is to think through the order and start gathering images. 

Also I made it a checklist for you so you can track progress
